### ISSUE TITLE
Compatibility with Rocket.Chat 3.11.0 is broken

### ISSUE THREAD

**Issue by cuonghuunguyen** [RocketChat/Apps.Rasa#19]
In RC 3.11.0 you guys added a "feature" that the conversation will not be auto-assigned to an offline or unavailable bot agent.
Therefore the Rasa App is currently broken with 3.11.0 because the bot agent user will always be offline.

Please tell me how could I deal with this problem. Thank you very much

**Comment by murtaza98** [comment]
U can set the user status to `online` via [this](https://docs.rocket.chat/api/rest-api/methods/users/setstatus) rest endpoint.
Note once u set the user status to online, it will remain the same until

1. U either log in to the bot account manually by signing in with it's username or password, or
2. U change the status via this same rest endpoint

**Comment by cuonghuunguyen** [comment]
Thank you for the solution. It seems to be the only workaround for us right now.
