### ISSUE TITLE
Handoff action.py?

### ISSUE THREAD

**Issue by bshowket** [RocketChat/Apps.Rasa#25]
Not an issue, most likely I haven't figured something obvious. 

Setup done according to instruction. Everything works, except handoff to human agent.

Do I need to write an custom action for handoff, as I saw in setting has default handoff Department in app setting, I thought it was handled by rasa.app.

Thanks in advance.

**Comment by bshowket** [comment]
this is the log i can see after ask to transfer

> Instance: mFLeQ7gAjHo4JgzBd
> debug: 2021-05-06T09:56:29.591Z Caller: anonymous OR constructor
> [
>   "callback's post is being executed...",
>   {
>     "method": "post",
>     "headers": {
>       "host": "192.168.20.244:3000",
>       "content-type": "application/json",
>       "accept": "*/*",
>       "accept-encoding": "gzip, deflate",
>       "user-agent": "Python/3.8 aiohttp/3.6.3",
>       "content-length": "83"
>     },
>     "query": {},
>     "params": {},
>     "content": {
>       "recipient_id": "iGtweT539jrfXQzsy",
>       "text": "Alright, I'll try to transfer you."
>     }
>   }
> ]
> info: 2021-05-06T09:56:29.592Z Caller: post -> post
> [
>   "Endpoint received a request"
> ]
> debug: 2021-05-06T09:56:29.656Z Caller: anonymous OR constructor
> [
>   "callback's post was successfully executed."
> ]

**Comment by murtaza98** [comment]
Hey @bshowket Are you referring to the custom action on Rasa? If so then yes, you'll have to define a custom action there which will trigger an handover by using the app's endpoint. [Here's](https://github.com/murtaza98/Sales-bot-in-Rasa/blob/d921566ca17e1eb541343409f9b2d3a157fe0a7c/actions.py#L128) a sample action I'd developed for testing for your reference.

**Comment by bshowket** [comment]
> Hey @bshowket Are you referring to the custom action on Rasa? If so then yes, you'll have to define a custom action there which will trigger an handover by using the app's endpoint. [Here's](https://github.com/murtaza98/Sales-bot-in-Rasa/blob/d921566ca17e1eb541343409f9b2d3a157fe0a7c/actions.py#L128) a sample action I'd developed for testing for your reference.

yes thats right! thanks for your help.
