### ISSUE TITLE
[New Feature] Add Synchronous handover support in the App

### ISSUE THREAD

**Issue by murtaza98** [RocketChat/Apps.Rasa#3]
Sync handover support means - When the bot is not able to answer the user's query N no of times continuously, then the app will automatically transfer control from Bot to an online Livechat Agent.

**Comment by murtaza98** [comment]
The implementation for this feature is will be a bit tricky than Dialogflow due to the following reason:-

1. Unlike Dialogflow, which provides a property `isFallback` within all its response, Rasa's API response(see references) doesn't have this property.
2. Unlike Dialogflow which provides the `detected-Intent-Name` within all its response, Rasa's API response doesn't include this.


My proposed solution to tackle this issue:-
1. Provide a additional `App-Setting` with named `Fallback Intent Name`. 
2. After making HTTP call to get response for query, make another HTTP call to [`/conversations/{sender-Id}/tracker`](https://rasa.com/docs/rasa/api/http-api/#operation/getConversationTracker) endpoint. The response from this enpoint will contain `last_message.intent` property which we can compare with the `App-Setting` in Step 1.

## References

- Rasa rest api response
```
[
   {
      "recipient_id":"session-no-1",
      "text":"Here some IPL quick info:\n1.The match between Team Stokes and Team Buttler was recently held and Team Stokes won."
   },
   {
      "recipient_id":"session-no-1",
      "text":"2.The next match is Ireland vs New Zealand on 02 July 2020"
   },
   {
      "recipient_id":"session-no-1",
      "text":"Did that help you?",
      "buttons":[
         {
            "payload":"Yes! it did",
            "title":"Yes! it did"
         },
         {
            "payload":"No! it didn't",
            "title":"No! it didn't"
         }
      ]
   }
]
```

**Comment by engahmed1190** [comment]
@murtaza98 it can be sent from RASA Chatbot itself where Fallback Action to be triggered after N times and Flag to be raised 

```
class ActionDefaultFallback(Action): 

def name(self): return "my_fallback_action"

def run(self, dispatcher, tracker, domain):
    i = tracker.get_slot('i')
    dispatcher.utter_message("okay")
    if i == 3:  // N =3 
        dispatcher.utter_message("Handoff ")
        return [ConversationPaused()]

    if i == None:
        i = 0
    i += 1
    return [UserUtteranceReverted(),SlotSet("i", i)]
```

**Comment by murtaza98** [comment]
@engahmed1190 Thanks for sharing this info. This should work :+1:
