### ISSUE TITLE
transfer to department not working as intended

### ISSUE THREAD

**Issue by bshowket** [RocketChat/Apps.Rasa#30]
Hi Folks,

One department setup for only rasa bot. 2 department setup with live agent(Status and Complains). In Admin>Apps>Rasa we use Complains as default channel.

![image](https://user-images.githubusercontent.com/27852269/117969558-77c9bd00-b31f-11eb-80b9-cebf08678d5a.png)

But Transferring to department to "Status" going in default department complains.

![image](https://user-images.githubusercontent.com/27852269/117968963-b1e68f00-b31e-11eb-9e2b-0e5c8c77cd38.png)

Am i missing something?
Thanks in advance.

**Comment by guimvmatos** [comment]
Hi @bshowket, 

I don't know how to help, but maybe you can help me.

I'm trying to do a handover too, but I don't know to the get the sessionid. Can you help me with this?

**Comment by murtaza98** [comment]
Hey @bshowket This seems to be a typo. You have an extra `'`(quote) within your request payload. It should be `"targetDepartment": "Status"`, but your request contains `"'targetDepartment": "Status"` in the targetDepartment key

**Comment by bshowket** [comment]
> Hey @bshowket This seems to be a typo. You have an extra `'`(quote) within your request payload. It should be `"targetDepartment": "Status"`, but your request contains `"'targetDepartment": "Status"` in the targetDepartment key

Thanks, yes you got that right , that was causing because of the typo

**Comment by bshowket** [comment]
> Hi @bshowket,
> 
> I don't know how to help, but maybe you can help me.
> 
> I'm trying to do a handover too, but I don't know to the get the sessionid. Can you help me with this?

i used as below:
`'sessionId': tracker.sender_id
`
