### ISSUE TITLE
how to get the sessionID?

### ISSUE THREAD

**Issue by guimvmatos** [RocketChat/Apps.Rasa#32]
Hi, 

I need to get the sessionID to perform a handover, but I don't know how. Can someone help me with this?

**Comment by murtaza98** [comment]
Hey @guimvmatos To quote the docs [here](https://github.com/RocketChat/Apps.Rasa/blob/master/docs/api-endpoints/perform-handover.md#perform-handover), 
> Session Id is the same session of Rasa

[Here's](https://github.com/murtaza98/Sales-bot-in-Rasa/blob/d921566ca17e1eb541343409f9b2d3a157fe0a7c/actions.py#L142) the exact code i used in my bot in Rasa to get this value there

**Comment by guimvmatos** [comment]
Hi again @murtaza98 , 

So, this `tracker.sender_id` is intrinsic to rasa? I don't have to declare it and I can get this value on any project?

I'll try again today, with this new information.

**Comment by guimvmatos** [comment]
Hi @murtaza98 , 

It works. thanks!!
